### ISSUE TITLE
Users can't confirm their account

### ISSUE THREAD

**Issue by Cryhex** [OFFLINE-GmbH/oc-mall-plugin#180] opened 2019-04-11 19:53 UTC
There is a problem when an user creates his account.
If the registration requires mail confirmation, the user receives an email (offline.mall::mail.customer.created) with this button:

{% partial 'button' url=**link** type='positive' body %}
Confirm account
{% endpartial %}

But the button is rendered without url attribute. In particular the variable **link** is empty.
How can I resolve it?
Thanks!!!

**Comment by tobias-kuendig** [comment] 2019-04-12 05:13
The mall plugin integrates with the RainLab.User plugin, so we do not handle account confirmation.

I think the mail that is sent is `rainlab.user::mail.activate`. 

Can you confirm that the issue is not with the mall plugin?

**Comment by tobias-kuendig** [comment] 2019-04-12 05:16
https://github.com/rainlab/user-plugin/issues/32

Make sure you've set up the `Account` component correctly, including the `:code` variable:

https://github.com/rainlab/user-plugin#account-component

**Comment by Cryhex** [comment] 2019-04-12 09:26
I'm using "myaccount" and "signup" componets of mall plugin, and this components don't have code parameter... I'm using "Mall Starter" theme (without changes)... thank you for your support..

**Comment by tobias-kuendig** [comment] 2019-04-12 16:17
I have added support for this feature in `1.2.4` which is currently available via edgeUpdates. Would you have time to test this?

Just make sure to update your `offline.mall::mail.customer.created` partial to match the new contents:

https://github.com/OFFLINE-GmbH/oc-mall-plugin/blob/245cf7ccc0b4a90a3526680db16bfde37c9e77f1/views/mail/customer/created.htm

Everyhting else should work out of the box once you've updated the plugin to version 1.2.4.

**Comment by Cryhex** [comment] 2019-04-13 16:40
Yes, I can test it.. but how can I update the plugin via edgeUpdates? I'm sorry but I don't know it!
Thank you!

**Comment by tobias-kuendig** [comment] 2019-04-15 05:17
You have to set the `cms.edgeUpdates` setting to `true` and update your October installation.

**Comment by Cryhex** [comment] 2019-04-16 09:40
Yes, it seems to work well!
Some little arrangements:
1) "_Your user account enables you to keep track of open and past orders._" in new email template would be after the confirm button.
2) If the user make a login without email confirmation, he gets an error message like "wrong credential" instead of something like "account waiting confirmation".
3) The confirm button redirect to cart page, where I can modify redirecting link?
Thank you!

**Comment by tobias-kuendig** [comment] 2019-04-19 16:53
The login error has been fixed in 12bec21 which is available as edge update as v1.2.6. Thank you very much for this input and the testing!

**Closed by tobias-kuendig** 2019-04-19 16:53 UTC
