### ISSUE TITLE
OFFLINE\Mall\Models\ShippingMethod

### ISSUE THREAD

**Issue by adoudiet** [OFFLINE-GmbH/oc-mall-plugin#937] opened 2022-06-13 06:49 UTC
Hello,
I have the error when customer valide with paiement offline.
Symfony\Component\Debug\Exception\FatalThrowableError: Type error: Return value of OFFLINE\Mall\Models\ShippingMethod::jsonSerialize() must be an instance of OFFLINE\Mall\Models\mixed, array returned in /home/httpd/vhosts/volenvalais.ch/httpdocs/plugins/offline/mall/models/ShippingMethod.php:246
October V1, Mall 2.0.1

Thank for your service
Best Regard Alain

**Comment by chocolata** [comment] 2022-06-22 10:11
Hi, 

Just updated to ^2.0 and am encountering a similar issue as you describe here.
In my case the error is thrown when I try to add an item to my shopping cart.

`Return value of OFFLINE\Mall\Models\ShippingMethod::jsonSerialize() must be an instance of OFFLINE\Mall\Models\mixed, array returned" on line 246 of E:\xxx\xxx\_xampp\htdocs\xxx\plugins\offline\mall\models\ShippingMethod.php`

@tobias-kuendig Do you have an idea what might be causing this?

Thanks for your work.

**Comment by chocolata** [comment] 2022-08-15 15:47
Just to let you know, when I remove the `: mixed` from line `237` at `\htdocs\xxx\plugins\offline\mall\models\ShippingMethod.php`

`public function jsonSerialize(): mixed`

The issue is resolved in my case. Seems a bit counter intuïtive. Can we fix follow-up on this?

**Comment by tobias-kuendig** [comment] 2022-08-16 05:10
This is probably because you run PHP 7.4? `: mixed` was only added in PHP 8.

Fixed in a9db1a8

Thanks for the report!

**Comment by chocolata** [comment] 2022-08-16 07:34
Hi Tobias, yes, I am running PHP 7.4.30 as a matter of fact. Tricky, those compatibility issues, especially when older plugins don't get updated as quickly. Thanks for your great work again... The OFFLINE Mall kicks ass.

**Comment by Pixinside** [comment] 2022-08-22 12:23
Using October 3.0.67 and running php8.1 I had to add back the :mixed to make it work. Otherwise I got this error:

```
Declaration of OFFLINE\Mall\Models\ShippingMethod::jsonSerialize() must be compatible with Illuminate\Database\Eloq  
  uent\Model::jsonSerialize(): mixed
```

**Comment by mjauvin** [comment] 2022-09-12 20:07
@tobias-kuendig Should be closed as completed.

**Comment by tobias-kuendig** [comment] 2022-09-13 05:03
Thanks!

**Closed by tobias-kuendig** 2022-09-13 05:03 UTC
