### ISSUE TITLE
[BUG]Properties Tab Not Displaying

### ISSUE THREAD

**Issue by letthewriterswrite** [OFFLINE-GmbH/oc-mall-plugin#123] opened 2019-02-03 02:50 UTC
Even though a properties group is set with the category, the properties tab suddenly has broken.

![image](https://user-images.githubusercontent.com/13875478/52171975-1bcd6280-272c-11e9-9414-f338059bf173.png)

**Comment by amdad** [comment] 2019-02-04 03:43
I found out that, at least one Property in each category, need to have "Use for Variants". Then properties will show up. Without it, none properties will show up even in Single Article mode. That's a bug or at least, bad UX, because user doesn't now he needs to set at least property to be used even in Variant mode. I think it should be treated as bug because in many categories/ or even whole shops there will be no need for Product Variants. Still Properties should work. 

Last changes about showing this info (which is good)

![image](https://user-images.githubusercontent.com/10062429/52188744-ca5cca80-2834-11e9-8409-678a698e51c5.png)

go a little bit to far here:

https://github.com/OFFLINE-GmbH/oc-mall-plugin/commit/e0c4caa48e49c6afcc0d401e62a17a8c90ddd754#diff-63ed7e5cae428d74f99abce3e255bda1R358

because properties shouldn't be hidden when in Single Article mode

**Comment by tobias-kuendig** [comment] 2019-02-04 06:33
This was introduced in the latest version, thanks for the bug report.

The issue is fixed now.

**Closed by tobias-kuendig** 2019-02-04 06:33 UTC
