### ISSUE TITLE
Variants are no longer attached to products with 3.0.22 update

### ISSUE THREAD

**Issue by cyril-design** [OFFLINE-GmbH/oc-mall-plugin#1046] opened 2023-08-01 13:25 UTC
Since the update to version 3.0.22 all my products have "lost" their variants.

`The selected category has no Variant properties defined. Please switch the inventory management method to "Article" or select another category.`

Yet everything seems correct in the corresponding tables...
On my local demo version (with a fresh `php artisan mall:seed-demo`) I have the same problem with this update.

PS. I updated from version 3.0.20 to 3.0.22

Thanks for your help

**Comment by yellotra** [comment] 2023-08-01 15:29
Yes, I also faced this bug after update

**Comment by tobias-kuendig** [comment] 2023-08-02 06:08
Can you share your October CMS versions? I was not able to reproduce the issue. Also, when do you see the variants "error message"? When you open an existing product?

Looking at the commits from 3.0.20 to 3.0.22 only translation strings and a composer version restraint changed:

https://github.com/OFFLINE-GmbH/oc-mall-plugin/compare/v3.0.20...v3.0.21

**Comment by yellotra** [comment] 2023-08-02 09:51
This bug appears if update 3.4.10 to 3.4.11

**Comment by cyril-design** [comment] 2023-08-02 10:55
Same here. OctoberCMS update to 3.4.11.

The bug appears when I edit or create a product.
The error message is catch in Product model line 616 ( `if (count($this->getGroupByPropertyIdOptions()) < 2)` ...).

Here is some weird behavior:
If I checked then unchecked a category, I can see my variants attached to an existing product but the select field for Attribute for variant grouping is empty.
However when I edit the category product, I can see products in tab section.
Here a link to [my screen capture](https://streamable.com/4hs0fv) (expires in 2 days).

**Comment by cyril-design** [comment] 2023-08-02 11:36
In Product model I trace log the query pivot in filter.
It's returns `NULL` instead of `INTEGER`

```/**
     * We are using a simple dropdown for this attribute since the relation
     * widget has some problems with the emptyOption option.
     * @return array
     */
    public function getGroupByPropertyIdOptions()
    {
        return ['' => trans('offline.mall::lang.common.none')]
            + $this->categories->flatMap->properties->filter(function ($q) {
                trace_log(gettype($q->pivot->use_for_variants));
                return $q->pivot->use_for_variants;
            })->pluck('name', 'id')->toArray();
    }```

**Comment by tobias-kuendig** [comment] 2023-08-02 11:45
Thank you guys, this is fixed in version 3.0.23.

A previously missing check on the relationship constraints was added to the October library. This broke previously working code in Mall that should have been broken to begin with.

Fix 3ca3d06

commit to library: https://github.com/octobercms/library/commit/7fc8a8c1aebf9feb87dfbedfaae1801a6f3acb91

**Comment by quiz1k** [comment] 2023-08-02 11:59
Hi @tobias-kuendig, you changed doens't work properly.
I faced with same issue.  Something went wrong with pivot. After update October CMS to v3.4.11 some of data stopped to returns. Below I attached 2 screenshots. The first one - what's return on v3.4.10 and the next one what's return on v3.4.11.
The error caused in file plugins/offline/mall/models/Property.php
in that block of code 
```
    public $belongsToMany = [
        'property_groups' => [
            PropertyGroup::class,
            'table'      => 'offline_mall_property_property_group',
            'key'        => 'property_id',
            'otherKey'   => 'property_group_id',
            'pivot'      => ['use_for_variants', 'filter_type', 'sort_order'],
            'pivotModel' => PropertyGroupProperty::class,
        ],
    ];
```
![Return on v3.4.10](https://github.com/OFFLINE-GmbH/oc-mall-plugin/assets/131185307/6e7142fc-fb38-4d11-a2fa-183e579624e3)
Return on v3.4.10

![Return on v3.4.11](https://github.com/OFFLINE-GmbH/oc-mall-plugin/assets/131185307/ae7e7209-68dc-4bf7-b652-1bcf9f6a13e0)
Return on v3.4.11

**Comment by cyril-design** [comment] 2023-08-02 12:15
Sorry, the fix doesn't works for me too...

**Comment by tobias-kuendig** [comment] 2023-08-02 13:16
> Below I attached 2 screenshots. The first one - what's return on v3.4.10 and the next one what's return on v3.4.11.

Where did you add this dump? Where do you see that data missing?

**Comment by quiz1k** [comment] 2023-08-02 13:20
> > Below I attached 2 screenshots. The first one - what's return on v3.4.10 and the next one what's return on v3.4.11.
> 
> Where did you add this dump? Where do you see that data missing?

I added this dump to plugins/offline/mall/components/productsfilter/property.htm on the 14th line.

**Comment by quiz1k** [comment] 2023-08-02 13:28
> > Below I attached 2 screenshots. The first one - what's return on v3.4.10 and the next one what's return on v3.4.11.
> 
> Where did you add this dump? Where do you see that data missing?

There is the same dump but on different versions. 
Error:
![image (1)](https://github.com/OFFLINE-GmbH/oc-mall-plugin/assets/131185307/4d89b52f-e2a3-4c33-a8eb-c57780ce6b18)
For some reason fileds "use_for_variants", "filter_type", "sort_order" are not returned on the October CMS v3.4.11.

**Comment by tobias-kuendig** [comment] 2023-08-03 06:29
The offending commit has been reverted upstream: https://github.com/octobercms/library/commit/d2ae52849bac01e48fcdb6f7c7cfea57f14b5208

Let's wait and see if another solution will be integrated.

For the time being, just stay on 3.4.10:

```
composer require october/rain:3.4.10 october/all:3.4.10
```

**Comment by tobias-kuendig** [comment] 2023-08-05 14:59
Version [v3.4.12](https://github.com/octobercms/library/releases/tag/v3.4.12) of the library has been released. Can you update your dependencies and check if the issue is gone with the new library version?

Thank you!

**Comment by quiz1k** [comment] 2023-08-05 15:09
Hi @tobias-kuendig, thank you for notifying.  It fixed my issue. Thanks!

**Comment by tobias-kuendig** [comment] 2023-08-07 04:34
Thank you for reporting and testing it! 👍️

**Closed by tobias-kuendig** 2023-08-07 04:34 UTC
