### ISSUE TITLE
Conflict reviews and add to cart buttons

### ISSUE THREAD

**Issue by dizakids** [OFFLINE-GmbH/oc-mall-plugin#548] opened 2020-08-02 21:42 UTC
I installed the mall theme for hosting there all the reviews are also not displayed when you reload the page, the reviews appear and the add to cart button disappears in a second, the reviews disappear, the add to cart button appears (there is clearly some kind of conflict). This is a link to the test site https://js-studio.site/en/product/produkt-1
Help me figure it out please

**Comment by tobias-kuendig** [comment] 2020-08-03 06:36
It looks like this commit is causing the issue. For the time being, you can uncomment the added line. I will see what the problem is.

https://github.com/OFFLINE-GmbH/oc-mall-plugin/commit/75eba778eb1f6f278326d716ad154e05b50a53fb

**Comment by tobias-kuendig** [comment] 2020-08-04 13:50
This is fixed in 1ccae01 and will be released later today. Thank you @dizakids!

**Closed by tobias-kuendig** 2020-08-04 13:50 UTC

**Comment by dizakids** [comment] 2020-08-07 09:42
Thank you. Reviews are displayed correctly, but there is still no way to add a review
