### ISSUE TITLE
Stripe payment not working with Quick Checkout 

### ISSUE THREAD

**Issue by lyordey** [OFFLINE-GmbH/oc-mall-plugin#677] opened 2020-12-14 00:16 UTC
The problem comes from a Javascript error at line 86 in the file /classes/payments/stripe/form.htm that makes the execution stopped at this line.

The variable `form` is undefined when the process is launched by a single click on the payment button. With "Quick Checkout", the payment button is not of type "submit" and the `form` variable of the initStripe() function cannot be defined, as there is no element in the page having the id "mall-payment-form".

By switching the lines 86 and 87, like shown bellow, the payment works fine :

Line 86 `if ($form.length) {`
Line 87 `var submit = form.querySelector('.oc-loading')`

**Comment by Zmove** [comment] 2020-12-14 09:23
I confirm the issue and the solution. Thanks

**Comment by mjauvin** [comment] 2020-12-26 16:57
Looks to me like there's a problem with the variable identifier as well (missing the "$"), should be like so:
```
                var $form = $('#mall-payment-form')
                if ($form.length) {
                   var submit = $form.querySelector('.oc-loading')
```
I'll submit a PR

**Comment by mjauvin** [comment] 2020-12-26 17:09
Duplicate of #674

**Closed** 2020-12-28 08:10 UTC
Labels: bug, help wanted
