### ISSUE TITLE
Usernames instead of Email

### ISSUE THREAD

**Issue by markusobi0** [OFFLINE-GmbH/oc-mall-plugin#183] opened 2019-04-15 17:08 UTC
Not everyone want to login and register using a E-Mail, how about adding the possibility to use Usernames instead

**Comment by tobias-kuendig** [comment] 2019-04-16 07:04
We are using RainLab.User which supports this. You can implement your own [`SignInHandler`](https://github.com/OFFLINE-GmbH/oc-mall-plugin/blob/develop/classes/customer/SignInHandler.php) and [`SignUpHandler`](https://github.com/OFFLINE-GmbH/oc-mall-plugin/blob/develop/classes/customer/SignUpHandler.php) to use this feature.

We might add an out-of-the-box option in a future version but this has very low priority at the moment since it can be implemented with the provided interfaces.

**Comment by markusobi0** [comment] 2019-04-16 18:18
Thanks for this tip.

**Comment by chrisvidal** [comment] 2019-05-22 08:02
@markusobi0 Did you manage to implement your own signin / signup handler?

**Comment by tobias-kuendig** [comment] 2021-05-29 12:32
Closing this as duplicate of #172

**Closed by tobias-kuendig** 2021-05-29 12:32 UTC
