### ISSUE TITLE
Orders Export

### ISSUE THREAD

**Issue by skacco** [OFFLINE-GmbH/oc-mall-plugin#707] opened 2021-01-13 10:15 UTC
I see in the controllers/orders/_list_toolbar.htm a button for export order that is commented 

I try this button but it does not work
"Call to undefined method OFFLINE\Mall\Models\Order::commaSeparated()"
It is under development?

**Comment by tobias-kuendig** [comment] 2021-01-18 06:56
There is a [`OrderExport`](https://github.com/OFFLINE-GmbH/oc-mall-plugin/blob/develop/models/OrderExport.php) model that exports data. I honestly don't remember the state of the export feature. It is more than three years old.

You should be able to get this working by fixing the `exportData` method in the OrderExport model.

You can find the missing models on our old `oc-snipcart-shop` plugin, which was the base for oc-mall:
https://github.com/OFFLINE-GmbH/oc-snipcartshop-plugin/blob/develop/models/Order.php#L78

These two methods should live on the `OrderExport` model, not on the `Order` as it is currently expected.

**Comment by tobias-kuendig** [comment] 2021-05-29 13:15
Closing this as duplicate of #98

**Closed by tobias-kuendig** 2021-05-29 13:15 UTC
