### ISSUE TITLE
Complex Discount mode

### ISSUE THREAD

**Issue by faselunare** [OFFLINE-GmbH/oc-mall-plugin#306] opened 2019-09-01 23:00 UTC
Add different discount mode (like prestashop)
Three tabs

INFO
- Name
- Description
- Code (optional, if no code follow the conditions) add button to auto generate the code
- published/unpublished

CONDITIONS
1. Single client discount
A discount created only for a specific user
2. Add "Valid from" (date) along with end date
3. Minimum quantity
minimum amount in the cart (with or with out taxes / with or with out shipping cost)
4. total discount available for each customer (how many time a customer can use this rule)
5. Restriction: by user group, by product/products

ACTIONS
- Free shipping yes/no
- Discount % or fixed or nothing (with taxes or without taxes)
- Apply to: whole order, less expensive product in the cart, specific product/products*

*if i have a discount of 2 euro for example on a product type
and i have many products of the same type in the cart, each product should have 2€ of discount

**Comment by PubliAlex** [comment] 2019-09-02 07:16
I would also add choice of price field for which you want to apply the discount in actions.

**Comment by tobias-kuendig** [comment] 2019-09-03 14:55
I like these ideas, thanks! Discounts will be reworked in a future release so we will keep these points in mind.

**Comment by PubliAlex** [comment] 2019-09-03 15:00
In my opinion, such a discount system could (and should) replace the old_price field. I like multiple price field feature, but it should be kept only to manage different price lists. not to manage different prices for the same price list.

If the complex discount system allow to apply the discount to all, or to a specific price field, you could manage different price lists with the possibiliy to apply different discounts for different price lists, which allow to handle all possible case.

**Comment by chrisvidal** [comment] 2019-11-05 05:09
I would love to be able as a developer to create my own discount business logic. Clients are coming up with so many crazy discount business logic that it is impossible to cater for all the cases.
Would it be possible to implement something like the mechanism used for the Signin and Signup handlers?

**Comment by tobias-kuendig** [comment] 2019-11-05 06:42
Sure! That would be the optimal goal. Unfortunately this feature will be quite a lot of work and I don't know when I get around to implement something.

**Comment by PubliAlex** [comment] 2021-03-31 13:33
I love building ecommerce websites using mall, but it's true that most of the customer insatisfaction come from the limitation of discount possibilities.

I wonder where it is on the roadmap, and what we could do as a community, to help, cause I would also be frustrated to not be able to propose mall when starting a new ecommerce system, because I know that the discount system will not fit the client needs.

Best regards,

**Comment by tobias-kuendig** [comment] 2021-04-02 16:03
I currently do not have any ressources to develop a new system, it looks like it's going to be a lot of work.

If anyone feels up for the task, it should be possible to develop a new discount system as a standalone plugin with which interested people could experiment and provide feedback.

Integrating the new system into the plugin itself will also require a good strategy to migrate existing discounts.

**Comment by tobias-kuendig** [comment] 2021-05-29 13:24
Closing this as duplicate of #375

**Closed by tobias-kuendig** 2021-05-29 13:24 UTC
