### ISSUE TITLE
cartButton.cart.products.count not consistent

### ISSUE THREAD

**Issue by RobertCh2** [OFFLINE-GmbH/oc-mall-plugin#520] opened 2020-05-29 14:03 UTC
1. When you add product to cart, it is counting (adding) the the quantity of pieces added to the cart.
2. When you reload the page it displays the number of product (kinds of products) in the cart. 
3. So if you add for example 2 pieces of some product to the empty cart, it will display the number »2« . After reloading the page it will display the number »1« .
4. Furthermore, if you add another »2« pieces of another product, it will display the number »3«. After reloading the page it will display the number »2«. And so on.

How to deal with this? It is very confusing for user...

**Comment by tobias-kuendig** [comment] 2020-06-01 08:12
Can you reproduce the issue on our demo website? https://mall.offline.swiss/

If so, can you tell me how? What code did you use to update the cart counter? Did you use [this example from the docs](https://offline-gmbh.github.io/oc-mall-plugin/components/cart.html#example-implementations)?

**Comment by tobias-kuendig** [comment] 2020-06-01 10:51
Ah yes, that's because the same products are merged when they are being added to the cart. 

I have added two new event properties to make this easier: `data.new_items_count` and `data.new_items_quantity` will now return the effective values from the cart _after_ the product was added. You can use either one to update your counter on the frontend (requires version 1.11.16):

```js
$(function () {
    var $count = $('.js-count');
    $.subscribe('mall.cart.productAdded', function (e, data) {
        // You have access to different values here.
        // console.log(data.item); // All item data
        // console.log(data.quantity); // Added quantity
        // console.log(data.new_items_count); // New total items in cart
        // console.log(data.new_items_quantity); // New total quantity of items in cart
        $count.text(data.new_items_count);
        // /* or */ $count.text(data.new_items_quantity);
    });
    $.subscribe('mall.cart.productRemoved', function (e, data) {
        // You have access to different values here.
        // console.log(data.item); // All item data
        // console.log(data.quantity); // Removed quantity
        // console.log(data.new_items_count); // New total items in cart
        // console.log(data.new_items_quantity); // New total quantity of items in cart
        $count.text(data.new_items_count);
        // /* or */ $count.text(data.new_items_quantity);
    });
});
```

**Closed by tobias-kuendig** 2020-06-01 10:51 UTC
