### ISSUE TITLE
Error when trying to get grouped_properties

### ISSUE THREAD

**Issue by vosco88** [OFFLINE-GmbH/oc-mall-plugin#809] opened 2021-07-28 12:11 UTC
Hi I am trying to display grouped properties according to the [docs](https://offline-gmbh.github.io/oc-mall-plugin/development/product-model.html#grouped-values), I am running OCMS 2.

However I am getting this error:
`Trying to get property 'id' of non-object in /data/2/1/219596a6-26ca-4afa-a2e1-f243ddc21d91/unitedcognacbottlebank.com/web/plugins/offline/mall/classes/traits/PropertyValues.php:51`

And related question can I get properties from specific group only?

**Comment by tobias-kuendig** [comment] 2021-07-29 05:30
Thank you for this report! This is a duplicate of #780, please follow this issue for updates on this problem.

**Closed by tobias-kuendig** 2021-07-29 05:30 UTC
