### ISSUE TITLE
How to override validation rules in SignUpHandler

### ISSUE THREAD

**Issue by nolyboms** [OFFLINE-GmbH/oc-mall-plugin#705] opened 2021-01-08 12:06 UTC
Only virtual products are sold on website and there is no need for the user to fill out the address/shipping information.

I am currently commenting out according rules in the file 

``` plugins/offline/mall/classes/customer/DefaultSignUpHandler.php ```

...which is of course a bad approach.

Can someone please help me to figure out how to override the rules so e.g. billing_lines,  shipping_lines etc. would not be required when signing up?

**Comment by tobias-kuendig** [comment] 2021-01-11 07:38
This is currently not a very well designed part of the plugin. One option is to [register your own SignupHandler implementation](https://github.com/OFFLINE-GmbH/oc-mall-plugin/blob/f07371d533bf07c6d3a022be307a8d7fb38832f0/classes/registration/BootServiceContainer.php#L37) that extends the default one and overrides the validation rules.

But this is overkill for most use cases. https://github.com/OFFLINE-GmbH/oc-mall-plugin/issues/172 tracks a related issue. Once we make the sign up fields more dynamic, custom validation should be easier to implement as well.

**Comment by nolyboms** [comment] 2021-03-22 09:52
Tried countless ways but none fitted in into the logic signupHandler, customer, order address, etc.
#172 seems to me to be one of the most needed improvement of the plugin.

**Comment by tobias-kuendig** [comment] 2021-05-29 13:22
Closing this as duplicate of #172

**Closed by tobias-kuendig** 2021-05-29 13:22 UTC
