### ISSUE TITLE
Add discount type "Valid for products in category"

### ISSUE THREAD

**Issue by alxy** [OFFLINE-GmbH/oc-mall-plugin#157] opened 2019-03-07 10:59 UTC
Sometimes you may want to give a discount to all products of a specific category. With the current setup, this is very tedious, as you need to create a discount for each single product separtely.

**Comment by tobias-kuendig** [comment] 2019-03-07 13:49
Great idea! :+1:

**Comment by alxy** [comment] 2019-03-07 14:08
However, this would require a major rework of the discount implementation. Right now, all dicounts apply to the entire cart and are not specific to products. A few things I noted when trying to implement this one:

* No matter what discount type, the discount always applys to the entire cart. Meaning an alternate price for one specific product will actually make the cart total fixed to that alternate price. I think this is a bug, as the alternate price should certainly only apply to the selected product. Otherwise you could add infinetly many products without increasing the price.
* Some discounts cannot be combined with other dicounts as they [fix the total amount](https://github.com/OFFLINE-GmbH/oc-mall-plugin/blob/develop/classes/cart/DiscountApplier.php#L67). I am not sure why this is - isnt it perfectly valid to have a code for free shipping along with some other general discount? We might need to implement an option to allow discounts to be combined with other discounts or not.
* I have not yet investiated this point, but according to the code all discounts are applied after taxes - which is fine from the customers point of view, however taxed prices cannot be discounted of course. Is the tax calculation beeing done correctly in this case? The demo theme does not show taxes, so I could not really see it there.

**Comment by alxy** [comment] 2019-03-07 14:38
I have also already started to implement this, so if it is of some use for anyone: https://github.com/alxy/oc-mall-plugin/commit/465ace0699a015b2c1fba650146423cbd6b294cc

**Comment by Almusamim** [comment] 2019-03-13 11:56
And sometimes you would want to have the same discount for multiple products which are not necessary from the same category.

> Sometimes you may want to give a discount to all products of a specific category. With the current setup, this is very tedious, as you need to create a discount for each single product separtely.

**Comment by alxy** [comment] 2019-03-21 09:58
I have thought about this and think the best option would be to have an extendable system, as with the payment methods. This includes having an abstract base class `Discount` with a required abstract method `public abstract function apply(Cart $cart)` and possibly a `isValid(Cart $cart)` function. The class should be able to specify its own form config to freely configure what the discount should do and when it is applicable. That allows for very complex discounts defined by other plugins (extensions).

The default discount form should also include a switch if the discount can be combined with other discounts.

Problems I see with this approach is that it may get more complex to actually calculate the discounted amounts, however, in the long term I think this major rework will pay out.

**Comment by tobias-kuendig** [comment] 2021-05-29 12:30
Closing this as duplicate of #375

**Closed by tobias-kuendig** 2021-05-29 12:30 UTC
