### ISSUE TITLE
Delivery cost is not displayed in the backend and in the user's mail if delivery method have rates

### ISSUE THREAD

**Issue by igor-tv** [OFFLINE-GmbH/oc-mall-plugin#361] opened 2019-10-27 18:16 UTC
If the conditions -> rates are configured in the delivery method, then the delivery cost  is not displayed in the backend and in in the letter to the user Confirmation for order (offline.mall :: mail.checkout.succeeded).

**Comment by dathwa** [comment] 2019-11-28 15:47
I can confirm this bug in OCMS build 458 with Mall 1.8.2.
I added new shipping rates by weight.
The delivery cost (in the email and on customer order details) shows the default cost, not the calculated cost by weight.
However, the total calculated price is correct. 
Anyone got a fix for this?

**Comment by marcogrueter** [comment] 2020-01-23 17:01
Can confirm this bug too, although it seems to be just a display bug.

My scenario: 1 shipping method, empty price in the general tab, 6 rates by weight set up.

Change `{{ order.shipping.method.price_formatted | raw }}` to `{{ order.totalShippingPostTaxes() | raw }}` in:

- component orderslist -> partial productlist, line 78
- e-mail template 'mall.order.table', line 86
- controllers\orders\_items.htm, line 105 - slightly different: `<?= e($order->totalShippingPostTaxes()) ?>`

to get the correct shipping amounts.

If some from OFFLINE could confirm that this is indeed the way to go, I will gladly put up a PR and go on the hunt for more instances of `oder.shipping.method.price_formatted`.

**Comment by dathwa** [comment] 2020-02-19 14:51
Alas, the PDF invoice also shows ZERO for shipping if the shipping rates by weight are applied.
This issue seems to me serious, and I'm surprised no-one else is flagging this.
Any chance of a fix in the Master soon? 
This particular issue needs to be addressed in the theme. In `themes/xxx/partials/mallPDF/order/table.htm` swap `{% partial 'mallPDF/order/shipping' shipping=order.shipping %}` for` {% partial 'mallPDF/order/shipping' shipping=order.shipping order=order %}`.
In themes/xxx/partials/mallPDF/order/shipping.htm swap `{{ shipping.method.price_formatted }}` for `{{ order.totalShippingPostTaxes() | raw }}`

**Comment by tobias-kuendig** [comment] 2020-02-19 15:08
If you already have a working solution, PRs are always very welcome! :gift_heart:

**Comment by dathwa** [comment] 2020-02-19 16:12
Hi Tobias. It's a very fair point. I really need to dive in and figure out this github thing.

**Comment by tobias-kuendig** [comment] 2020-02-20 06:31
If you have any questions regarding GitHub or submitting a PR feel free to ping me on Slack!

**Comment by tobias-kuendig** [comment] 2021-05-29 12:52
Added in 46106f2, Thanks for your work @marcogrueter.

**Closed by tobias-kuendig** 2021-05-29 12:52 UTC
