### ISSUE TITLE
Discount with Promo Code can be always be applied by same user

### ISSUE THREAD

**Issue by chrisvidal** [OFFLINE-GmbH/oc-mall-plugin#427] opened 2020-01-16 01:38 UTC
I have a clever customer who uses the same promo code for 75 different orders, and the discount code has been applied every time.
Would it make sense to limit the usage of a discount per user?

**Comment by chrisvidal** [comment] 2020-01-16 03:16
my attempt to fix this problem in the trait `OFFLINE\Mall\Classes\Traits\Cart\Discounts.php`

```php
public function applyDiscount(Discount $discount)
{
        $uniqueDiscountTypes = ['shipping'];
        // additional code
        $user = \Auth::getUser();
        $customer = $user->customer;
        $orders = \OFFLINE\Mall\Models\Order
                        ::where('customer_id', $customer->id)
                        ->get();
        // Failed Attempts of using direct json search in db
        // $orders = \DB::table('offline_mall_orders')
                    // ->where('customer_id', $customer->id)
                    // ->where('discounts->discount->code', 'PROMO1')
                    // ->whereRaw('JSON_EXTRACT(discounts, discounts) = ?', ['$."code"[0]'])
                    // ->whereRaw('JSON_CONTAINS(discounts->"$[*].code", "PROMO1")')
                    // ->whereRaw('JSON_CONTAINS(discounts,\'{"code": "PROMO1"}\')')
                    // ->whereRaw('JSON_CONTAINS(discounts, \'{"code": "PROMO1"}\', \'$.discount\')')
                    // ->whereRaw('JSON_SEARCH(discounts->"$.discount.$.code", \'one\', \'PROMO1\') IS NOT NULL')
                    // ->whereRaw('JSON_SEARCH(discounts, \'one\', \'PROMO1\')')
                    // ->get();

        $collection = new \Illuminate\Database\Eloquent\Collection;
        $collection = $orders->filter(function($order) use ($discount) {
            if (! empty($order->discounts)) {
                $discounts = $order->discounts;
                foreach ($discounts as $appliedDiscount) {
                    $appliedDiscount = $appliedDiscount['discount'];
                    if ($appliedDiscount['trigger'] == 'code'
                        && $discount->code == $appliedDiscount['code']) {
                        return true;
                    }
                }
            }
            return false;
        });

        if ($collection->count() > 0)
            throw new ValidationException([trans('offline.mall::lang.discounts.validation.expired') . ' You already used this code.' ]);

```

**Comment by tobias-kuendig** [comment] 2020-01-16 06:27
I guess the best solution here is if we keep a log of what customer has applied what discount separately. This way we can limit the usage to 1 time per customer and also have a nice log to do analytics on.

Thank you for this input!

**Comment by chrisvidal** [comment] 2020-01-16 06:39
I guess we already have the log in the order table somehow, in the JSON field

**Comment by chrisvidal** [comment] 2020-01-16 07:43
along that line I implemented another feature that might be handful and easy to implement if you decide to go with this new table relationship user-discount ~
For my project, I had to be able to assign a discount to a particular user.

in my case, such a discount will be created for a user who win at playing a game that we developed (a cool rock paper scissors :) ).

the full user story:
- user is playing to the game
- he wins the game
- he is attributed a discount (only for his account) that he can apply during checkout

I think this feature would be handy and easy to implement - just a relationship between a discount and a user, applyDiscount to be updated accordingly.

I can probably work on a partial PR for that, let me know

**Comment by tobias-kuendig** [comment] 2020-01-16 08:07
Definitely, the whole discount system needs a complete overhaul. See #375.

**Comment by chrisvidal** [comment] 2020-02-06 05:57
do you think you will create this new relationship user-discountApplied in a coming future version?

just to get a sense if I do it now on my side of thing first or wait a bit.

thanks @tobias-kuendig

**Comment by tobias-kuendig** [comment] 2021-05-29 12:49
Closing this as duplicate of #375

**Closed by tobias-kuendig** 2021-05-29 12:49 UTC
