### ISSUE TITLE
Problem with Paypal Payment

### ISSUE THREAD

**Issue by jonnydevv** [OFFLINE-GmbH/oc-mall-plugin#143] opened 2019-02-22 17:53 UTC
Hello,

I'm not sure if I'm missing any step on configuration for PayPal payment.
This is what I get when after begin checkout:
<img width="1259" alt="screenshot 2019-02-22 at 16 48 56" src="https://user-images.githubusercontent.com/2188826/53260884-30b16c00-36c2-11e9-8e55-da476464e194.png">
No input to enter any email or anything.
I've already setup PayPal Rest Api to use test mode with Paypal App Cliente ID and Paypal Secret.

**Comment by tobias-kuendig** [comment] 2019-02-22 18:06
This partial doesn't seem to be included correctly. Could you try to debug it?

https://github.com/OFFLINE-GmbH/oc-mall-plugin/blob/develop/components/paymentmethodselector/method.htm#L28


Did you overwrite some partials? Did you give the component an alias?

Thank you!

**Comment by jonnydevv** [comment] 2019-02-23 13:30
For what I see in your component when i dump _method.payment_provider_ `{% set path = __SELF__ ~ '::gateways/' ~ (method.payment_provider) %}` there should be a partial "paypal-rest". But I can't find any partial for PayPal-rest in [oc-mall-plugin](https://github.com/OFFLINE-GmbH/oc-mall-plugin/tree/develop/components/paymentmethodselector/gateways). Should be anything else  beside save `payment information` button? Also seems like there should be another partial called `offline` for invoice payment. 
Another thing, event with this I was able to save payment information and proceed to next step 
<img width="643" alt="screenshot 2019-02-23 at 12 14 40" src="https://user-images.githubusercontent.com/2188826/53286928-a110c980-3764-11e9-963e-2909cf858058.png">
 I was able to finish the payment and was sent back.
<img width="688" alt="screenshot 2019-02-23 at 12 17 34" src="https://user-images.githubusercontent.com/2188826/53286960-141a4000-3765-11e9-84a5-e992b8006f6d.png">
As you can see, the payments were successful but they appear as payment pending.
<img width="908" alt="screenshot 2019-02-23 at 12 20 03" src="https://user-images.githubusercontent.com/2188826/53286996-8c810100-3765-11e9-9a26-1205e205deb1.png">

Hope this helps, let me know if you need more testing.

**Comment by tobias-kuendig** [comment] 2019-02-23 15:47
Sorry, I didn't get the problem yesterday. The Paypal provider does not have any configuration values for the user to enter so there is no partial to display. 

If you want to add a custom message to display when the user select "Paypal" simply create the partial in your theme folder and it will be included. 

It's odd that your payments are marked as "pending". Do you see the payments in your backend under Orders -> Payments?

**Comment by jonnydevv** [comment] 2019-02-23 16:37
In the backend there is no payments in Orders -> payments. This is what I get in Orders -> orders:
<img width="1101" alt="screenshot 2019-02-23 at 15 36 08" src="https://user-images.githubusercontent.com/2188826/53289091-cdd2da00-3780-11e9-828a-16edcbc07b9f.png">

**Comment by tobias-kuendig** [comment] 2019-02-23 16:54
It looks like the return redirect from PayPal is not detected as such.

If you're being returned from PayPal this conditional should catch on and handle the rest:
https://github.com/OFFLINE-GmbH/oc-mall-plugin/blob/develop/components/Checkout.php#L152

**Comment by tobias-kuendig** [comment] 2019-02-26 07:10
@jonnydevv 	Were you able to fix your checkout flow? If not I'm happy to help.

**Comment by jonnydevv** [comment] 2019-02-26 10:28
Hello,

Sorry for late response.
I've been testing it yesterday. It seems like it doesn't work only on localhost using vhost. I 've pushed to remote and is works on remote. I think it should work on local tho, but it's ok for me.

Thank you very much!

**Comment by tobias-kuendig** [comment] 2019-02-26 11:00
Thank you for the feedback. Is it possible that your localhost adds an additional redirect when the user returns from PayPal? Like https:// -> http:// or www -> non-www? 

In any case this problem should not occur even with an additional redirect. I'll take a closer look at it since the problem you're experiencing on localhost might happen to someone in production.

**Comment by jonnydevv** [comment] 2019-02-26 12:06
Just in case it helps, when returned from PayPal, my url is kept the same. I always use vhost with local tld eg:. http://domain.local. In this case, when returned, I'm returned with http://domain.local, the correct domain.

**Comment by Apoculos** [comment] 2019-02-27 22:25
GREAT plugin, like it very much so far! 

I'm having a similar payment pending problem for Paypal and stripe on both local dev/remote. I've even tried configuring a SSL in case that was the issue. The payment is definitely going through to stripe/paypal.. as I'm getting receipt urls/etc in the data returned. The error log receives "Could not mark paid order as paid" and "Could not log successful payment" in both of the errors the "response" part is empty.. so not sure if that is a clue! Let me know if I can provide anymore info to help solve this. 

"response":"[object] (Omnipay\\Stripe\\Message\\Response: {})"

**Comment by tobias-kuendig** [comment] 2019-02-28 07:53
Thank you very much @Apoculos and @jonnydevv. Could either one of you update to `v1.1.8` and check the system.log after a checkout? The original exception is now logged in full. It would help me debug this problem if you could post the exception that gets logged with the `OFFLINE.Mall` log entries.

**Comment by Apoculos** [comment] 2019-02-28 14:40
Here is a copy paste of the errors now. Definitely some good clues! For me the problem is fixed by upping the varchar character count to 500 on the "payment_method' column of "offline_mall_payments_log"

Thanks for the quick response tobias-kuendig.


[2019-02-28 14:19:48] development.ERROR: OFFLINE.Mall: Could not log successful payment.
 at /www/catselman/vendor/laravel/framework/src/Illuminate/Database/Connection.php:664, Doctrine\\DBAL\\Driver\\PDOException(code: 22001): SQLSTATE[22001]: String data, right truncated: 1406 Data too long for column 'payment_method' at row 1 at /www/catselman/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:107, PDOException(code: 22001): SQLSTATE[22001]: String data, right truncated: 1406 Data too long for column 'payment_method' at row 1 at /www/catselman/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:105)
[stacktrace]
#0 /www/catselman/vendor/laravel/framework/src/Illuminate/Database/Connection.php(624): Illuminate\\Database\\Connection->runQueryCallback('insert into `of...', Array, Object(Closure))
#1 /www/catselman/vendor/laravel/framework/src/Illuminate/Database/Connection.php(459): Illuminate\\Database\\Connection->run('insert into `of...', Array, Object(Closure))
#2 /www/catselman/vendor/laravel/framework/src/Illuminate/Database/Connection.php(411): Illuminate\\Database\\Connection->statement('insert into `of...', Array)
#3 /www/catselman/vendor/laravel/framework/src/Illuminate/Database/Query/Processors/Processor.php(32): Illuminate\\Database\\Connection->insert('insert into `of...', Array)
#4 /www/catselman/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(2159): Illuminate\\Database\\Query\\Processors\\Processor->processInsertGetId(Object(October\\Rain\\Database\\QueryBuilder), 'insert into `of...', Array, 'id')
#5 /www/catselman/vendor/october/rain/src/Database/QueryBuilder.php(276): Illuminate\\Database\\Query\\Builder->insertGetId(Array, 'id')
#6 /www/catselman/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(1283): October\\Rain\\Database\\QueryBuilder->insertGetId(Array, 'id')
#7 /www/catselman/vendor/october/rain/src/Database/Builder.php(178): Illuminate\\Database\\Eloquent\\Builder->__call('insertGetId', Array)
#8 /www/catselman/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(722): October\\Rain\\Database\\Builder->__call('insertGetId', Array)
#9 /www/catselman/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(687): Illuminate\\Database\\Eloquent\\Model->insertAndSetId(Object(October\\Rain\\Database\\Builder), Array)
#10 /www/catselman/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(550): Illuminate\\Database\\Eloquent\\Model->performInsert(Object(October\\Rain\\Database\\Builder))
#11 /www/catselman/vendor/october/rain/src/Database/Model.php(747): Illuminate\\Database\\Eloquent\\Model->save(Array)
#12 /www/catselman/vendor/october/rain/src/Database/Model.php(780): October\\Rain\\Database\\Model->saveInternal(Array)
#13 /www/catselman/vendor/laravel/framework/src/Illuminate/Support/HigherOrderTapProxy.php(34): October\\Rain\\Database\\Model->save()
#14 /www/catselman/plugins/offline/mall/classes/payments/PaymentResult.php(240): Illuminate\\Support\\HigherOrderTapProxy->__call('save', Array)
#15 /www/catselman/plugins/offline/mall/classes/payments/PaymentResult.php(214): OFFLINE\\Mall\\Classes\\Payments\\PaymentResult->logPayment(false, Array, Object(Omnipay\\Stripe\\Message\\Response))
#16 /www/catselman/plugins/offline/mall/classes/payments/PaymentResult.php(87): OFFLINE\\Mall\\Classes\\Payments\\PaymentResult->logSuccessfulPayment(Array, Object(Omnipay\\Stripe\\Message\\Response))
#17 /www/catselman/plugins/offline/mall/classes/payments/Stripe.php(80): OFFLINE\\Mall\\Classes\\Payments\\PaymentResult->success(Array, Object(Omnipay\\Stripe\\Message\\Response))
#18 /www/catselman/plugins/offline/mall/classes/payments/DefaultPaymentGateway.php(75): OFFLINE\\Mall\\Classes\\Payments\\Stripe->process(Object(OFFLINE\\Mall\\Classes\\Payments\\PaymentResult))
#19 /www/catselman/plugins/offline/mall/classes/payments/PaymentService.php(60): OFFLINE\\Mall\\Classes\\Payments\\DefaultPaymentGateway->process(Object(OFFLINE\\Mall\\Models\\Order))
#20 /www/catselman/plugins/offline/mall/components/Checkout.php(214): OFFLINE\\Mall\\Classes\\Payments\\PaymentService->process()
#21 /www/catselman/modules/cms/classes/ComponentBase.php(187): OFFLINE\\Mall\\Components\\Checkout->onCheckout()
#22 /www/catselman/modules/cms/classes/Controller.php(850): Cms\\Classes\\ComponentBase->runAjaxHandler('onCheckout')
#23 /www/catselman/modules/cms/classes/Controller.php(740): Cms\\Classes\\Controller->runAjaxHandler('checkout::onChe...')
#24 /www/catselman/modules/cms/classes/Controller.php(373): Cms\\Classes\\Controller->execAjaxHandlers()
#25 /www/catselman/modules/cms/classes/Controller.php(224): Cms\\Classes\\Controller->runPage(Object(Cms\\Classes\\Page))
#26 /www/catselman/modules/cms/classes/CmsController.php(50): Cms\\Classes\\Controller->run('checkout/confir...')
#27 [internal function]: Cms\\Classes\\CmsController->run('checkout/confir...')
#28 /www/catselman/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(54): call_user_func_array(Array, Array)
#29 /www/catselman/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(45): Illuminate\\Routing\\Controller->callAction('run', Array)
#30 /www/catselman/vendor/laravel/framework/src/Illuminate/Routing/Route.php(212): Illuminate\\Routing\\ControllerDispatcher->dispatch(Object(Illuminate\\Routing\\Route), Object(Cms\\Classes\\CmsController), 'run')
#31 /www/catselman/vendor/laravel/framework/src/Illuminate/Routing/Route.php(169): Illuminate\\Routing\\Route->runController()
#32 /www/catselman/vendor/laravel/framework/src/Illuminate/Routing/Router.php(658): Illuminate\\Routing\\Route->run()
#33 /www/catselman/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(30): Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#34 /www/catselman/plugins/rainlab/translate/classes/LocaleMiddleware.php(29): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#35 /www/catselman/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): RainLab\\Translate\\Classes\\LocaleMiddleware->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#36 /www/catselman/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#37 /www/catselman/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(41): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#38 /www/catselman/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\\Routing\\Middleware\\SubstituteBindings->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#39 /www/catselman/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#40 /www/catselman/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#41 /www/catselman/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\\View\\Middleware\\ShareErrorsFromSession->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#42 /www/catselman/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#43 /www/catselman/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(63): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#44 /www/catselman/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\\Session\\Middleware\\StartSession->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#45 /www/catselman/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#46 /www/catselman/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#47 /www/catselman/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\\Cookie\\Middleware\\AddQueuedCookiesToResponse->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#48 /www/catselman/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#49 /www/catselman/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(66): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#50 /www/catselman/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\\Cookie\\Middleware\\EncryptCookies->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#51 /www/catselman/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#52 /www/catselman/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(102): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#53 /www/catselman/vendor/laravel/framework/src/Illuminate/Routing/Router.php(660): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#54 /www/catselman/vendor/laravel/framework/src/Illuminate/Routing/Router.php(635): Illuminate\\Routing\\Router->runRouteWithinStack(Object(Illuminate\\Routing\\Route), Object(Illuminate\\Http\\Request))
#55 /www/catselman/vendor/laravel/framework/src/Illuminate/Routing/Router.php(601): Illuminate\\Routing\\Router->runRoute(Object(Illuminate\\Http\\Request), Object(Illuminate\\Routing\\Route))
#56 /www/catselman/vendor/october/rain/src/Router/CoreRouter.php(20): Illuminate\\Routing\\Router->dispatchToRoute(Object(Illuminate\\Http\\Request))
#57 /www/catselman/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(176): October\\Rain\\Router\\CoreRouter->dispatch(Object(Illuminate\\Http\\Request))
#58 /www/catselman/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(30): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}(Object(Illuminate\\Http\\Request))
#59 /www/catselman/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(46): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#60 /www/catselman/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\\Foundation\\Http\\Middleware\\CheckForMaintenanceMode->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#61 /www/catselman/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#62 /www/catselman/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(102): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#63 /www/catselman/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(151): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#64 /www/catselman/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(116): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter(Object(Illuminate\\Http\\Request))
#65 /www/catselman/index.php(43): Illuminate\\Foundation\\Http\\Kernel->handle(Object(Illuminate\\Http\\Request))
#66 {main}
"} 
[2019-02-28 14:19:48] development.CRITICAL: OFFLINE.Mall: Could not mark paid order as paid. ","exception":"[object] (ErrorException(code: 0): Undefined variable: payment at /www/catselman/plugins/offline/mall/classes/payments/PaymentResult.php:97)
[stacktrace]
#0 /www/catselman/plugins/offline/mall/classes/payments/PaymentResult.php(97): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleError(8, 'Undefined varia...', '/www/catselman/...', 97, Array)
#1 /www/catselman/plugins/offline/mall/classes/payments/Stripe.php(80): OFFLINE\\Mall\\Classes\\Payments\\PaymentResult->success(Array, Object(Omnipay\\Stripe\\Message\\Response))
#2 /www/catselman/plugins/offline/mall/classes/payments/DefaultPaymentGateway.php(75): OFFLINE\\Mall\\Classes\\Payments\\Stripe->process(Object(OFFLINE\\Mall\\Classes\\Payments\\PaymentResult))
#3 /www/catselman/plugins/offline/mall/classes/payments/PaymentService.php(60): OFFLINE\\Mall\\Classes\\Payments\\DefaultPaymentGateway->process(Object(OFFLINE\\Mall\\Models\\Order))
#4 /www/catselman/plugins/offline/mall/components/Checkout.php(214): OFFLINE\\Mall\\Classes\\Payments\\PaymentService->process()
#5 /www/catselman/modules/cms/classes/ComponentBase.php(187): OFFLINE\\Mall\\Components\\Checkout->onCheckout()
#6 /www/catselman/modules/cms/classes/Controller.php(850): Cms\\Classes\\ComponentBase->runAjaxHandler('onCheckout')
#7 /www/catselman/modules/cms/classes/Controller.php(740): Cms\\Classes\\Controller->runAjaxHandler('checkout::onChe...')
#8 /www/catselman/modules/cms/classes/Controller.php(373): Cms\\Classes\\Controller->execAjaxHandlers()
#9 /www/catselman/modules/cms/classes/Controller.php(224): Cms\\Classes\\Controller->runPage(Object(Cms\\Classes\\Page))
#10 /www/catselman/modules/cms/classes/CmsController.php(50): Cms\\Classes\\Controller->run('checkout/confir...')
#11 [internal function]: Cms\\Classes\\CmsController->run('checkout/confir...')
#12 /www/catselman/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(54): call_user_func_array(Array, Array)
#13 /www/catselman/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(45): Illuminate\\Routing\\Controller->callAction('run', Array)
#14 /www/catselman/vendor/laravel/framework/src/Illuminate/Routing/Route.php(212): Illuminate\\Routing\\ControllerDispatcher->dispatch(Object(Illuminate\\Routing\\Route), Object(Cms\\Classes\\CmsController), 'run')
#15 /www/catselman/vendor/laravel/framework/src/Illuminate/Routing/Route.php(169): Illuminate\\Routing\\Route->runController()
#16 /www/catselman/vendor/laravel/framework/src/Illuminate/Routing/Router.php(658): Illuminate\\Routing\\Route->run()
#17 /www/catselman/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(30): Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#18 /www/catselman/plugins/rainlab/translate/classes/LocaleMiddleware.php(29): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#19 /www/catselman/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): RainLab\\Translate\\Classes\\LocaleMiddleware->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#20 /www/catselman/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#21 /www/catselman/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(41): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#22 /www/catselman/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\\Routing\\Middleware\\SubstituteBindings->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#23 /www/catselman/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#24 /www/catselman/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#25 /www/catselman/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\\View\\Middleware\\ShareErrorsFromSession->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#26 /www/catselman/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#27 /www/catselman/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(63): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#28 /www/catselman/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\\Session\\Middleware\\StartSession->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#29 /www/catselman/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#30 /www/catselman/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#31 /www/catselman/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\\Cookie\\Middleware\\AddQueuedCookiesToResponse->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#32 /www/catselman/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#33 /www/catselman/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(66): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#34 /www/catselman/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\\Cookie\\Middleware\\EncryptCookies->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#35 /www/catselman/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#36 /www/catselman/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(102): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#37 /www/catselman/vendor/laravel/framework/src/Illuminate/Routing/Router.php(660): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#38 /www/catselman/vendor/laravel/framework/src/Illuminate/Routing/Router.php(635): Illuminate\\Routing\\Router->runRouteWithinStack(Object(Illuminate\\Routing\\Route), Object(Illuminate\\Http\\Request))
#39 /www/catselman/vendor/laravel/framework/src/Illuminate/Routing/Router.php(601): Illuminate\\Routing\\Router->runRoute(Object(Illuminate\\Http\\Request), Object(Illuminate\\Routing\\Route))
#40 /www/catselman/vendor/october/rain/src/Router/CoreRouter.php(20): Illuminate\\Routing\\Router->dispatchToRoute(Object(Illuminate\\Http\\Request))
#41 /www/catselman/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(176): October\\Rain\\Router\\CoreRouter->dispatch(Object(Illuminate\\Http\\Request))
#42 /www/catselman/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(30): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}(Object(Illuminate\\Http\\Request))
#43 /www/catselman/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(46): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#44 /www/catselman/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\\Foundation\\Http\\Middleware\\CheckForMaintenanceMode->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#45 /www/catselman/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#46 /www/catselman/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(102): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#47 /www/catselman/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(151): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#48 /www/catselman/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(116): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter(Object(Illuminate\\Http\\Request))
#49 /www/catselman/index.php(43): Illuminate\\Foundation\\Http\\Kernel->handle(Object(Illuminate\\Http\\Request))
#50 {main}
"}

**Comment by tobias-kuendig** [comment] 2019-02-28 15:57
Thank you very much, @Apoculos. I've just released a new version with a fix for this problem. Please respond to this issue if the problem is not solved for you in v1.1.9.

**Closed by tobias-kuendig** 2019-02-28 15:57 UTC
