### ISSUE TITLE
Shipping Methods conditions

### ISSUE THREAD

**Issue by chrisvidal** [OFFLINE-GmbH/oc-mall-plugin#402] opened 2019-12-16 11:17 UTC
Could we add easily, on top of the country, the state in the shipping conditions tab?

**Comment by tobias-kuendig** [comment] 2019-12-16 11:29
I'm closing this as duplicate of https://github.com/OFFLINE-GmbH/oc-mall-plugin/issues/364

It's as "easy" as adding another relationship to the conditions model and checking it in the totals calculator class.

I would have to look into it myself to give you a proper answer. PRs welcome!

**Closed by tobias-kuendig** 2019-12-16 11:29 UTC
