### ISSUE TITLE
Rewrite product name if product uses Additional properties

### ISSUE THREAD

**Issue by romanseki** [OFFLINE-GmbH/oc-mall-plugin#159] opened 2019-03-09 13:15 UTC
I have product with product variants an If I add Addditional properties product name is rewrited by last of Additional property name

**Comment by tobias-kuendig** [comment] 2019-03-18 17:13
Thanks for your bug report! I'll see if I can re-produce the issue.

**Comment by papppeter** [comment] 2019-03-29 12:37
same happening to me.

steps:
create a product
add Additional properties
save

last one name will overwrite product name.

**Comment by tobias-kuendig** [comment] 2019-03-30 12:36
I'm currently unable to reproduce this issue. What do you mean by `add additional properties`? Are you creating a new Variant? Are you adding new properties to a category?

**Comment by romanseki** [comment] 2019-03-30 12:38
> I'm currently unable to reproduce this issue. What do you mean by `add additional properties`? Are you creating a new Variant? Are you adding new properties to a category?

Under product tab "Details" is "Additional properties" repeater

**Comment by tobias-kuendig** [comment] 2019-03-30 12:40
Now I've got it, thank you for the quick response! :+1:

**Comment by tobias-kuendig** [comment] 2019-03-30 13:02
This problem is related to RainLab.Translate. See https://github.com/rainlab/translate-plugin/issues/459 for further updates.

**Comment by tobias-kuendig** [comment] 2019-04-08 06:13
This problem was solved upstream. Once the new October Builds are available this problem will be fixed with the mall plugin as well.

Thank you for the bug report, @romanseki and @papppeter!

https://github.com/rainlab/translate-plugin/issues/459

**Closed by tobias-kuendig** 2019-04-08 06:13 UTC
