### ISSUE TITLE
Please, add the csv import function

### ISSUE THREAD

**Issue by sagjatome** [OFFLINE-GmbH/oc-mall-plugin#700] opened 2021-01-05 13:34 UTC
No more or less serious store can afford to manage goods manually. Importing goods from a file is just a necessity for a serious script.
Best Regards!

**Comment by tobias-kuendig** [comment] 2021-01-05 15:33
Duplicate of #98, you are welcome to submit a PR :+1:

**Closed by tobias-kuendig** 2021-01-05 15:33 UTC
