### ISSUE TITLE
Simple Checkout

### ISSUE THREAD

**Issue by HomaEEE** [OFFLINE-GmbH/oc-mall-plugin#107] opened 2019-01-19 13:34 UTC
Ordering on 1 page and with a minimum of fields to fill in - Name, phone number, email.
Or the ability to customize fields for ordering
For example - Ajax checkout for OpenCart

**Comment by tobias-kuendig** [comment] 2019-01-19 13:48
Thanks, closing as duplicate of https://github.com/OFFLINE-GmbH/oc-mall-plugin/issues/6

**Closed by tobias-kuendig** 2019-01-19 13:48 UTC
