### ISSUE TITLE
Question about Logout

### ISSUE THREAD

**Issue by chrisvidal** [OFFLINE-GmbH/oc-mall-plugin#297] opened 2019-08-28 06:55 UTC
Why do we clear the cart when a user is login out?
Wouldn't it be cool to retrieve your previous cart when you login back in the app?

**Comment by chrisvidal** [comment] 2019-08-28 07:08
ok my bad.  we are not destroying the cart when a user logs out.
we are actually keeping it.

what is happening is that a new cart is creating for the new session after logout.
Then if we login again, the session cart is transformed into a new cart and we end up with 2 cart for the same customer id. 

which is a serious problem.


scenario to test:

- login as a user
- add an item into cart
- logout user
- login same user
- cart is empty but database is holding 2 cars for the same customer id

**Comment by chrisvidal** [comment] 2019-08-28 07:09
my intuition is telling me that the guilty method is the `Cart::transferToCustomer()`

**Comment by tobias-kuendig** [comment] 2019-09-04 11:07
I guess the easiest way to fix this would be to merge both carts during login. But this might lead to unexpected behaviour. 

1. I'm adding a product to my cart
1. I don't want to buy it so I leave, my session expires
1. I come back a few days later to buy a product, during checkout I login and suddendly my cart contains two items!

**Comment by tobias-kuendig** [comment] 2019-09-04 12:58
I guess merging the cart is the better solution since no information gets lost. It might inflict some manual interaction on the user, but that's the trade-off here.

**Comment by tobias-kuendig** [comment] 2019-09-04 13:36
This feature has been implemented in a0d64c1. The carts are now merged with an old existing Cart during sign in.

**Closed by tobias-kuendig** 2019-09-04 13:36 UTC

**Comment by xyzqtc** [comment] 2022-08-05 12:42
Hey Tobias, I wonder why did you reverse the change?

https://github.com/OFFLINE-GmbH/oc-mall-plugin/commit/24ba7a3d9c297d2506bab22bed46cb6908046792

**Comment by tobias-kuendig** [comment] 2022-08-05 13:32
See #825

**Comment by xyzqtc** [comment] 2022-08-05 13:42
Ah can this be optional :D ? In settings maybe? I need the feature.. well I've modified the core files for this but still its nice to have.

**Comment by tobias-kuendig** [comment] 2022-08-08 05:30
If you submit a PR that introduces a setting I will gladly merge it! It can be placed on the GeneratlSettings form.
