### ISSUE TITLE
[Enhancement] Product upload from excel (xlsx or csv file)

### ISSUE THREAD

**Issue by bozsokidaniel** [OFFLINE-GmbH/oc-mall-plugin#169] opened 2019-03-23 09:21 UTC

**Comment by bozsokidaniel** [comment] 2019-03-23 09:24
Hi guys!

First, thank you for this great plugin! 👍 

What do you think about uploading products from excel table like xlsx or csv file? It would be much easier to upload multiple products.

**Comment by tobias-kuendig** [comment] 2019-03-25 10:53
Hi @bozsokidaniel 

Thank you for your input. I'm closing this issue as a duplicate of https://github.com/OFFLINE-GmbH/oc-mall-plugin/issues/98

See #98 for further infos.

**Closed by tobias-kuendig** 2019-03-25 10:53 UTC
