### ISSUE TITLE
Unable to delete properties

### ISSUE THREAD

**Issue by haralake** [OFFLINE-GmbH/oc-mall-plugin#335] opened 2019-10-02 12:34 UTC
I can create properties and also remove them from property groups tab but i can't delete them entirely. There is no option to delete properties that you don't use.

**Comment by tobias-kuendig** [comment] 2019-10-02 13:00
Thank you for this input! I'm closing this issue as a duplicate of https://github.com/OFFLINE-GmbH/oc-mall-plugin/issues/300.

**Closed by tobias-kuendig** 2019-10-02 13:00 UTC
